#!/bin/bash

echo "Enter the username you want to delete"

read name

a=`ls -l /home | grep $name`

if [ "$a" != "" ]; then	
	passwd -l $name
	pkill -u $name
	crontab -r -u $name
	userdel -r $name
	echo "User successfully deleted"
else
	echo "Username does not exist"
fi
